/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Elias (https://sketchfab.com/elias.voet)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-fighter-jet-719c014f040a46a3b54e90824da10c91
Title: Low poly Fighter Jet
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./assets/spaceship.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI * 3]} scale={0.2}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane_0" position={[0, 0, 0.36]} scale={[1, 1, 1.132]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Metal_Plates}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials['Glass.001']}
                />
              </group>
              <group
                name="Circle_1"
                position={[1.498, 0.803, -10.028]}
                rotation={[Math.PI / 2, -0.086, 0]}
                scale={[0.687, 0.445, 0.687]}>
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Metal_scratched}
                />
              </group>
              <group
                name="Circle001_2"
                position={[-2.617, 0.803, -10.051]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.687, 0.445, 0.687]}>
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials.Metal_scratched}
                />
              </group>
              <group
                name="Circle002_3"
                position={[2.617, 0.803, -10.051]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.687, 0.445, 0.687]}>
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.Metal_scratched}
                />
              </group>
              <group
                name="Circle003_4"
                position={[-1.498, 0.803, -10.028]}
                rotation={[Math.PI / 2, -0.086, 0]}
                scale={[0.687, 0.445, 0.687]}>
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.Metal_scratched}
                />
              </group>
              <group
                name="Circle004_5"
                position={[-2.617, 0.803, -10.051]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.61, 0.395, 0.61]}>
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials['Metal_scratched.001']}
                />
              </group>
              <group
                name="Circle005_6"
                position={[-1.498, 0.803, -10.028]}
                rotation={[Math.PI / 2, -0.086, 0]}
                scale={[0.61, 0.395, 0.61]}>
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials['Metal_scratched.002']}
                />
              </group>
              <group
                name="Circle006_7"
                position={[1.498, 0.803, -10.028]}
                rotation={[Math.PI / 2, -0.086, 0]}
                scale={[0.61, 0.395, 0.61]}>
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials['Metal_scratched.003']}
                />
              </group>
              <group
                name="Circle007_8"
                position={[2.617, 0.803, -10.051]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.609, 0.394, 0.609]}>
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials['Metal_scratched.004']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite001_9"
                position={[2.588, 0.629, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials['Fire_Mat.001']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite002_10"
                position={[2.588, 0.8, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials['Fire_Mat.002']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite003_11"
                position={[2.588, 0.8, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials['Fire_Mat.003']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite004_12"
                position={[1.511, 0.8, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials['Fire_Mat.004']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite005_13"
                position={[1.511, 0.8, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials['Fire_Mat.005']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite006_14"
                position={[1.511, 0.629, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_33"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_33.geometry}
                  material={materials['Fire_Mat.006']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite007_15"
                position={[1.511, 0.629, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_35"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_35.geometry}
                  material={materials['Fire_Mat.007']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite008_16"
                position={[-2.588, 0.629, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials['Fire_Mat.008']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite009_17"
                position={[-2.588, 0.629, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials['Fire_Mat.009']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite010_18"
                position={[-2.588, 0.8, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_41"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_41.geometry}
                  material={materials['Fire_Mat.010']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite011_19"
                position={[-2.588, 0.8, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials['Fire_Mat.011']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite012_20"
                position={[-1.512, 0.8, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_45"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_45.geometry}
                  material={materials['Fire_Mat.012']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite013_21"
                position={[-1.512, 0.8, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_47"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials['Fire_Mat.013']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite014_22"
                position={[-1.512, 0.629, -8.814]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_49"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials['Fire_Mat.014']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite015_23"
                position={[-1.512, 0.629, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_51"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials['Fire_Mat.015']}
                />
              </group>
              <group
                name="Animated_Fire_Sprite_33"
                position={[2.588, 0.629, -9.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}>
                <mesh
                  name="Object_53"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials.Fire_Mat}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/spaceship.glb')
